### ISSUE TITLE
rateLimit for each path has a common counter

### ISSUE THREAD

**Issue by doroved** [rayriffy/elysia-rate-limit#36]
If we set rateLimit for each Route, this limit will be shared. So if we use up the limit on one of the Routes, we will be blocked everywhere.
**Solution**: we need to keep a counter for each Route
```ts
const smsVerificationRoutes = new Elysia()
  .use(rateLimit())
  // your sms routes here

const apiRoutes = new Elysia()
  .use(rateLimit())
  // your api routes here

const server = new Elysia()
  .use(smsVerificationRoutes)
  .use(apiRoutes)
  .listen(3000)
```

Using guard does not help
```ts
const routerAuth = new Elysia().group('/auth', (app) =>
  app
    .guard((app) =>
      app
        .use(rateLimit())
...
```

**Comment by rayriffy** [comment]
This is not a bug. By default rateLimit context will be applied globally and disregarding any hierarchy, use [`scoping` option](https://github.com/rayriffy/elysia-rate-limit/blob/main/src/%40types/Options.ts#L17-L18) to make plugin affect per routes.

**Comment by rayriffy** [comment]
scoping is meant to separate rate limit per instances to grouping by each categories, by design rate limit should be counted globally this is also a default behavior for fastify, and express as well. If you want **per api route** you should create your own `generator` that's what it's designed for. this project should not cover every tiny cases otherwise it will be extremely bloated

**and do not make an accusation like that to anyone EVER**
